# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://Megha-Avee.github.io/'
baseurl:             'appdev/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Megha Agarwal
  url:               https://twitter.com/agarwal_megha26
  email:             megha@neonforlife.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
